#!/usr/bin/env python3
"""
Test script for SQL Injection Auditor
Demonstrates usage with a vulnerable test application
"""

import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from modules.crawler import InputVector
from modules.payload_engine import PayloadGenerator, DatabaseType, InjectionType
from modules.analysis_engine import VulnerabilityScanner, Vulnerability
from modules.verification import VulnerabilityVerifier
from modules.reporting import ReportGenerator, ScanSummary
from modules.waf_bypass import WAFBypassEngine
import requests
import time
from datetime import datetime

def create_test_vulnerabilities():
    """Create sample vulnerabilities for testing"""
    vulnerabilities = [
        Vulnerability(
            url="http://test.example.com/user.php",
            parameter="id",
            injection_type=InjectionType.ERROR_BASED,
            database_type=DatabaseType.MYSQL,
            payload="' OR 1=1 -- ",
            evidence="SQL syntax error detected",
            confidence=0.95,
            response_time=0.5,
            status_code=200,
            error_message="You have an error in your SQL syntax",
            database_info={"version": "5.7.33", "database": "testdb"}
        ),
        Vulnerability(
            url="http://test.example.com/search.php",
            parameter="q",
            injection_type=InjectionType.BOOLEAN_BASED,
            database_type=DatabaseType.POSTGRESQL,
            payload="' AND 1=1 -- ",
            evidence="Boolean-based response difference detected",
            confidence=0.85,
            response_time=0.3,
            status_code=200
        ),
        Vulnerability(
            url="http://test.example.com/admin/login.php",
            parameter="username",
            injection_type=InjectionType.UNION_BASED,
            database_type=DatabaseType.MSSQL,
            payload="' UNION SELECT 1,@@version,3 -- ",
            evidence="UNION-based response modification detected",
            confidence=0.90,
            response_time=0.8,
            status_code=200
        )
    ]
    
    return vulnerabilities

def test_payload_generation():
    """Test payload generation"""
    print("Testing Payload Generation...")
    generator = PayloadGenerator()
    
    # Test MySQL payloads
    mysql_payloads = generator.generate_all_payloads(DatabaseType.MYSQL)
    print(f"MySQL error-based payloads: {len(mysql_payloads['error_based'])}")
    print(f"MySQL boolean-based payloads: {len(mysql_payloads['boolean_based'])}")
    print(f"MySQL time-based payloads: {len(mysql_payloads['time_based'])}")
    print(f"MySQL union-based payloads: {len(mysql_payloads['union_based'])}")
    
    # Test WAF bypass
    original_payload = "' OR 1=1 -- "
    bypass_payloads = generator.generate_waf_bypass_payloads(original_payload)
    print(f"WAF bypass variations: {len(bypass_payloads)}")
    
    print("✓ Payload generation test passed\n")

def test_waf_bypass():
    """Test WAF bypass functionality"""
    print("Testing WAF Bypass...")
    waf_engine = WAFBypassEngine()
    
    # Test WAF detection
    test_headers = {
        'server': 'cloudflare',
        'cf-ray': '1234567890',
        'x-cdn': 'Incapsula'
    }
    test_content = "Access blocked by security firewall"
    
    detected_wafs = waf_engine.fingerprinter.detect_waf(test_headers, test_content)
    print(f"Detected WAFs: {detected_wafs}")
    
    # Test payload bypass
    payload = "' OR 1=1 -- "
    bypass_payloads = waf_engine.bypass_payload(payload, test_headers, test_content)
    print(f"Generated bypass payloads: {len(bypass_payloads)}")
    
    print("✓ WAF bypass test passed\n")

def test_reporting():
    """Test report generation"""
    print("Testing Report Generation...")
    
    # Create test data
    vulnerabilities = create_test_vulnerabilities()
    
    # Create scan summary
    scan_summary = ScanSummary(
        scan_date=datetime.now().isoformat(),
        target_url="http://test.example.com",
        total_vectors_tested=15,
        vulnerabilities_found=len(vulnerabilities),
        high_risk_vulnerabilities=2,
        medium_risk_vulnerabilities=1,
        low_risk_vulnerabilities=0,
        scan_duration=45.5,
        databases_detected=["mysql", "postgresql", "mssql"]
    )
    
    # Generate reports
    report_generator = ReportGenerator("test_reports")
    report_files = report_generator.generate_report(
        vulnerabilities,
        scan_summary=scan_summary,
        technical_details={
            "test_mode": True,
            "payloads_tested": 150,
            "verification_enabled": True
        },
        formats=['json']
    )
    
    print(f"Generated reports: {report_files}")
    
    # Check if JSON report was created
    if report_files and os.path.exists(report_files[0]):
        print(f"✓ Report file created: {report_files[0]}")
        
        # Read and display summary
        import json
        with open(report_files[0], 'r') as f:
            report_data = json.load(f)
        
        print(f"Report summary:")
        print(f"  Target: {report_data['scan_summary']['target_url']}")
        print(f"  Vulnerabilities: {report_data['scan_summary']['vulnerabilities_found']}")
        print(f"  High Risk: {report_data['scan_summary']['high_risk_vulnerabilities']}")
    
    print("✓ Report generation test passed\n")

def test_crawler():
    """Test crawler functionality"""
    print("Testing Crawler...")
    
    from modules.crawler import WebCrawler, VectorAnalyzer
    
    # Create test input vectors
    test_vectors = [
        InputVector(
            url="http://test.example.com/user.php?id=1",
            method='GET',
            params={'id': '1'}
        ),
        InputVector(
            url="http://test.example.com/login.php",
            method='POST',
            data={'username': 'admin', 'password': 'test'}
        )
    ]
    
    # Analyze vectors
    analyzer = VectorAnalyzer()
    analysis = analyzer.analyze_vectors(test_vectors)
    
    print(f"Total vectors: {analysis['total_vectors']}")
    print(f"GET vectors: {len(analysis['get_vectors'])}")
    print(f"POST vectors: {len(analysis['post_vectors'])}")
    print(f"High risk: {len(analysis['high_risk'])}")
    print(f"Medium risk: {len(analysis['medium_risk'])}")
    print(f"Low risk: {len(analysis['low_risk'])}")
    
    print("✓ Crawler test passed\n")

def run_all_tests():
    """Run all tests"""
    print("=" * 60)
    print("SQL INJECTION AUDITOR - TEST SUITE")
    print("=" * 60)
    
    try:
        test_payload_generation()
        test_waf_bypass()
        test_crawler()
        test_reporting()
        
        print("=" * 60)
        print("ALL TESTS PASSED ✓")
        print("=" * 60)
        
    except Exception as e:
        print(f"Test failed: {e}")
        import traceback
        traceback.print_exc()

if __name__ == '__main__':
    run_all_tests()
